### ISSUE TITLE
Can you port to Chrome?

### ISSUE THREAD

**Issue by ssrandur** [kuanyui/tooltip-jisyo#1]
感谢作者，从firefox安卓扩展过来的，使用体验良好，也想在电脑上使用（其它weblio字典都是英和字典）
由于看到作者是台湾人就直接使用中文请求了，如果造成不便很抱歉

**Comment by kuanyui** [comment]
1. It's impolite to open an issue in a foreign language in a project, which is obviously not related to such language. You should never assume no other people need to read existing issue. Please use AI to translate.
2. I'm not using Chrome, don't have time to implement the feature I don't need.
3. I don't understand Simplified Chinese.
